### ISSUE TITLE
[Bug]: `default-partition` configuration option doesn't seem to be used any more

### ISSUE THREAD

**Issue by NucciTheBoss** [charmed-hpc/slurmctld-operator#28]
After overhauling the API of the slurmctld operator, it doesn't look like the `default-partition` configuration option is used any more. The configuration option only seems to be reference within the `_on_config_changed(...)` hook and no where else within the charm:

https://github.com/charmed-hpc/slurmctld-operator/blob/71a32c435285d634e72fb29d0803fde1a789c738/src/charm.py#L139-L143

I tried to find references to `self._stored.default_partition` outside of the event handler, but it only seems to be referenced here. Should we hook this back up into _slurm.conf_, or am I missing something? Seems like the default partition is set to `Partition=DEFAULT Default=YES` and setting a new default partition using `juju config slurmctld default-partition=...` has no effect.

**Comment by jamesbeedy** [comment]
@NucciTheBoss It gets checked [here](https://github.com/charmed-hpc/slurmctld-operator/blob/71a32c435285d634e72fb29d0803fde1a789c738/src/interface_slurmd.py#L236) when the partition gets assembled.

**Comment by NucciTheBoss** [comment]
Thank you for pointing out the line! Will mark this as a question and close.
